"""Image-occlusion cards for the Spaced Repetition plugin: one label covered per card,
revealed IN PLACE on the image.

How it works: each diagram is a CSS background (embedded as a data URI in the vault CSS
snippet `.obsidian/snippets/rdh-occlusion.css`, so it renders on every device with no path
resolution). Each card is one line of HTML: the diagram plus ONE white box positioned over
one label. The box holds an SR cloze (==answer==). SR cloze cards redraw the whole card on
reveal, so the box shows [...] on the front and the term on the back, in the same spot.

Usage:
  .tools/.venv/bin/python .tools/occlusion_cards.py .tools/anatomy-diagrams.json \
      anat-oral-cavity anat-gingiva > /tmp/cards.md      # cards for the named diagrams
CSS snippet is (re)written for the named diagrams and must be enabled in appearance.json.
"""
import base64, io, json, sys
from pathlib import Path
from PIL import Image
sys.path.insert(0, str(Path(__file__).parent))
from occlude import render

ROOT = Path(__file__).resolve().parent.parent
CSS = ROOT / '.obsidian' / 'snippets' / 'rdh-occlusion.css'
PAD = 4          # px (200-dpi page) added around each label box
WIDTH = 1100     # px of the embedded image (sharp at full card width)

BASE_CSS = """/* generated by .tools/occlusion_cards.py — do not edit by hand */
.occ { container-type: inline-size; position: relative; width: 100%; background-size: 100% 100%; background-repeat: no-repeat; }
.occ-box { position: absolute; display: flex; align-items: center; justify-content: center;
  background: #fff; border: 2px solid #e8781e; border-radius: 6px; box-sizing: border-box;
  font-weight: 700; font-size: 2.5cqw; line-height: 1.1; text-align: center;
  padding: 0 0.4em; color: #222; white-space: normal; }
"""

def css_for(spec):
    page = Image.open(render(spec['pdf'], spec['pdf_page'])).convert('RGB')
    im = page.crop(spec['crop'])
    im = im.resize((WIDTH, round(im.height * WIDTH / im.width)), Image.LANCZOS)
    buf = io.BytesIO(); im.save(buf, 'JPEG', quality=85, optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode()
    return f".occ-{spec['name']} {{ background-image: url(data:image/jpeg;base64,{b64}); aspect-ratio: {im.width} / {im.height}; }}\n"

def card(spec, box, answer):
    cx0, cy0, cx1, cy1 = spec['crop']; w, h = cx1 - cx0, cy1 - cy0
    x0, y0 = box[0] - cx0 - PAD, box[1] - cy0 - PAD
    bw, bh = box[2] - box[0] + 2 * PAD, box[3] - box[1] + 2 * PAD
    pos = f"left:{100*x0/w:.2f}%;top:{100*y0/h:.2f}%;width:{100*bw/w:.2f}%;height:{100*bh/h:.2f}%"
    return f'<div class="occ occ-{spec["name"]}"><span class="occ-box" style="{pos}">=={answer}==</span></div>'

if __name__ == '__main__':
    specs = {s['name']: s for s in json.load(open(sys.argv[1]))}
    names = sys.argv[2:]
    CSS.parent.mkdir(parents=True, exist_ok=True)
    CSS.write_text(BASE_CSS + ''.join(css_for(specs[n]) for n in names))
    for n in names:
        for box, answer in specs[n]['labels']:
            print(card(specs[n], box, answer)); print()
